### PR TITLE
fix: hints option not updating correctly and hints section not visible in subggoal list

### LINKED ISSUE #2029: Hint toggle value not persisting in goal config modal
**Describe the bug**
When editing a goal, the "Hint" toggle is updated and correctly stored in the database. However, when attempting to edit the goal again, the "Hint" toggle state is not being passed to the Goal Config Modal, causing the toggle to appear in its default state instead of reflecting the stored value.

### LINKED ISSUE #2043: Hints not working on dev
**Describe the bug**
Hints are working on prod but not on dev (zinzen.vercel.app)

**To Reproduce**

1. Go to 'zinzen.vercel.app'
2. Create a Goal 'Learn Rust' with hints enabled
3. See there are no hints

**Expected behavior**
Hints appear just like on zinzen.me

### PR DESCRIPTION
**Pull request by vinaybadgujar102**
resolves #2043 
resolves #2029

### CODE REVIEW

**Review by tijlleenders — DISMISSED** [review]

File: src/api/GoalsAPI/index.ts [hunk 1]
```diff
@@ -348,7 +348,7 @@ export const getAllLevelGoalsOfId = async (id: string, resetSharedStatus = false
 export const addHintGoaltoMyGoals = async (goal: GoalItem) => {
```
Comment (Tushar-4781) [inline src/api/GoalsAPI/index.ts:348]: what if we use Promise.all here ?

**Review by Tushar-4781 — CHANGES_REQUESTED** [review]
can you resolve eslint warnings

**Comment by vinaybadgujar102** [comment]
@Tushar-4781 bump

**Review by Tushar-4781 — APPROVED** [review]
